### 1. 获取总数
GET https://api.vc.bilibili.com/link_draw/v1/doc/upload_count?uid=6591412
Accept: application/json

### 2. 获取所有数据
GET https://api.vc.bilibili.com/link_draw/v1/doc/doc_list?page_num=0&biz=all&uid=6591412&page_size=9
Accept: application/json



